apiVersion: apps/v1
kind: Deployment
metadata:
  name: jboss
  namespace: default
  labels:
    app: jboss
    environment: test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jboss
      environment: test
  template:
    metadata:
      labels:
        app: jboss
        environment: test
    spec:
      # serviceAccountName: jboss
      containers:
      - name: jboss
        image: 443102424924.dkr.ecr.us-west-2.amazonaws.com/aws-kia-dotcom-eks:jboss-runtime_e5d3bc9
        imagePullPolicy: IfNotPresent
        # command: ["tail", "-f", "/dev/null"]
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        - containerPort: 9990
          name: management
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
          requests:
            cpu: 125m
            memory: 512Mi
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: false
          runAsNonRoot: false
        # Health checks for JBoss
        # livenessProbe:
        #   httpGet:
        #     path: /
        #     port: 8080
        #   initialDelaySeconds: 120
        #   periodSeconds: 30
        #   timeoutSeconds: 10
        #   failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
      restartPolicy: Always 